name: Deploy Backend Ventas to AWS EC2

on:
  push:
    branches:
      - deploy 

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Login en Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build y Push de la Imagen Docker
        run: |
          # Construimos la imagen usando el Dockerfile de tu carpeta
          docker build -t ${{ secrets.DOCKER_USERNAME }}/back-ventas:latest ./Springboot-API-REST
          docker push ${{ secrets.DOCKER_USERNAME }}/back-ventas:latest

      - name: Despliegue en EC2 vía SSH (IE4 e IE7)
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Descargamos la nueva imagen y reiniciamos el contenedor
            docker pull ${{ secrets.DOCKER_USERNAME }}/back-ventas:latest
            docker stop back-ventas-container || true
            docker rm back-ventas-container || true
            docker run -d --name back-ventas-container -p 8080:8080 \
              -e DB_ENDPOINT=${{ secrets.DB_ENDPOINT }} \
              -e DB_PORT=3306 \
              ${{ secrets.DOCKER_USERNAME }}/back-ventas:latest